- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    homebrew_taps:
      # - homebrew/cask-cask
      # - caskroom/fonts

    homebrew_packages:
      - name: anyenv
      - name: awscli
      - name: direnv
      - name: git
      - name: jq
      - name: noti
      # - name: packer
      # - name: terraform
      - name: tree
      - name: wget
      - name: zsh

      # for phpenv
      - name: autoconf
      - name: automake
      - name: bison
      - name: libjpeg
      - name: libmcrypt
      - name: libpng
      - name: libxml2
      - name: re2c

    homebrew_cask_packages:
      - name: 1password
      - name: alfred
      - name: android-studio
      - name: appcleaner
      - name: boxcryptor
      # - name: clipy
      - name: discord
      - name: docker
      - name: dropbox
      - name: firefox
      # - name: flash-player
      # - name: font-fira-code
      - name: google-chrome
      - name: google-japanese-ime
      - name: iterm2
      # - name: mysqlworkbench
      - name: postman
      # - name: sequel-pro
      # - name: sketch
      - name: slack
      # - name: sublime-text
      # - name: teamviewer
      - name: tableplus
      - name: the-unarchiver
      - name: transmit
      # - name: vagrant
      # - name: virtualbox
      - name: visual-studio-code

  handlers:

  tasks:
    # brew tap
    # - name: install taps of homebrew
    #  homebrew_tap: tap="{{ item }}" state=present
    #  with_items: "{{ homebrew_taps }}"
    #  tags:
    #    - brew
    #    - cask

    # brew update
    - name: update homebrew
      homebrew: update_homebrew=yes
      tags:
        - brew

    # brew instal
    - name: install homebrew packages
      homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
      with_items: "{{ homebrew_packages }}"
      tags:
        - brew

    # brew cask install
    - name: install homebrew cask packages
      homebrew_cask: name="{{ item.name }}" state=present
      with_items: "{{ homebrew_cask_packages }}"
      tags:
        - cask
